### ISSUE TITLE
Defining taxon with int or string of taxonomy ID gives different results

### ISSUE THREAD

**Issue by DuncanSussfeld** [taxoniq/taxoniq#16]
Hi,
I have been a very happy user of taxoniq for a while now, and I have just noticed a small behaviour discrepancy that may cause some problems down the line if one isn't careful about this.

When defining a Taxon using the NCBI taxonomy ID, one can specify it as an int or as a string:
```
>>> t_int = taxoniq.Taxon(3041)
>>> t_int
taxoniq.Taxon(3041)
>>> t_str = taxoniq.Taxon('3041')
>>> t_str
taxoniq.Taxon(3041)
```

However, after doing so, the type of the taxon's `tax_id` attribute isn't the same:
```
>>> t_int.tax_id
3041
>>> t_str.tax_id
'3041'
 ```

This typing difference is then passed on to methods of the taxoniq module, as you can see below:
```
>>> [t.tax_id for t in t_int.lineage]
[3041, 33090, 2759, 131567, 1]
>>> [t.tax_id for t in t_str.lineage]
['3041', 33090, 2759, 131567, 1]
```
It also means that two `Taxon` objects defined from the same NCBI taxID, but with two different types, cannot be directly compared:
```
>>> t_int == t_str
False
```

I don't know if that is intentional or not, and there may be reasons to have this behaviour, but I feel like it could cause some problems to any user who isn't too careful about typing in Python -- which is probably a significant amount of people! So I figured I should bring that up in case it hasn't been noticed before.

Anyway, thank you very much for an remarkably useful package :)
Best,
Duncan

**Comment by kislyuk** [comment]
Thank you for pointing this out. You are absolutely correct that the input needs to be normalized to avoid this. I will push out a patch shortly.
