### ISSUE TITLE
using  nr/nt databases

### ISSUE THREAD

**Issue by aretchless** [taxoniq/taxoniq#25]
Hello. Taxoniq looks like it could be a useful tool for us, but we may need to [use the nr/nt databases](https://taxoniq.github.io/#using-the-nr-nt-databases). Unfortunately, the instructions for downloading those databases seem to be obsolete.  The ncbi files are not included as 'assets' for the the 1.0.0 and 1.0.1 releases. They are only available for v0.6.1.

Has anything changed, or would you still suggest using the databases distributed as assets for v0.6.1?

thanks
Adam

**Comment by kislyuk** [comment]
Thanks for inquiring about this Adam. I had a number of issues building the nt indexes for versions after 0.6.1, so there was a delay in releasing them. Indexes for core_nt are available with the latest release, v1.0.3.

I documented the switch from nt to core_nt in the readme file. The full nt database is no longer supported (although you can build the indexes yourself if you wish). Queries against the nr database were never supported so I removed mention of it from the readme file.

**Comment by aretchless** [comment]
Thank you.
